/*
 Copyright (c) 2021-2023. Sylvain Guillet (sylvain.guillet@tutamail.com)
 */
#ifndef PROPAGATOR_BASE_H
#define PROPAGATOR_BASE_H

#include <IntegratorBase.h>
#include <Spacecraft.h>

namespace IO::Astrodynamics::Maneuvers
{
    class ManeuverBase;
}

namespace IO::Astrodynamics::Propagators
{
    class Propagator
    {
    private:
        IO::Astrodynamics::Maneuvers::ManeuverBase *m_standbyManeuver{nullptr};
        const IO::Astrodynamics::Body::Spacecraft::Spacecraft &m_spacecraft;
        IO::Astrodynamics::Integrators::IntegratorBase &m_integrator;
        IO::Astrodynamics::Time::Window<IO::Astrodynamics::Time::TDB> m_window;
        std::vector<IO::Astrodynamics::OrbitalParameters::StateVector> m_stateVectors{};
        std::vector<std::vector<IO::Astrodynamics::OrbitalParameters::StateOrientation>> m_StateOrientations{};

    public:
        /**
         * @brief Construct a new Propagator Base object
         * 
         * @param spacecraft Spacecraft to propagate
         * @param integrator Integrator to use
         * @param window Time window propagation
         */
        Propagator(const IO::Astrodynamics::Body::Spacecraft::Spacecraft &spacecraft, const IO::Astrodynamics::Integrators::IntegratorBase &integrator, const IO::Astrodynamics::Time::Window<IO::Astrodynamics::Time::TDB> &window);

        /**
         * @brief Set the Standby Maneuver
         * 
         * @param standbyManeuver 
         */
        void SetStandbyManeuver(IO::Astrodynamics::Maneuvers::ManeuverBase *standbyManeuver);

        /**
         * @brief Propagate
         * 
         */
        void Propagate();

        /**
         * @brief Find the nearest lower state vector from an epoch
         * 
         * @param epoch 
         * @return const IO::Astrodynamics::OrbitalParameters::StateVector*
         */
        [[nodiscard]] const IO::Astrodynamics::OrbitalParameters::StateVector *FindNearestLowerStateVector(const IO::Astrodynamics::Time::TDB &epoch) const;

        /**
         * @brief Add a state vector
         * 
         * @param sv State vector
         */
        void AddStateVector(const IO::Astrodynamics::OrbitalParameters::StateVector &sv);

        /**
         * @brief Add a state orientation
         * 
         * @param so State orientation
         */
        void AddStateOrientation(const IO::Astrodynamics::OrbitalParameters::StateOrientation &so);

        /**
         * @brief Erase data from a given epoch up to end
         * 
         * @param epoch 
         */
        void EraseDataFromEpochToEnd(const IO::Astrodynamics::Time::DateTime &epoch);

        /**
         * @brief Get the State Vectors generated by propagator
         * 
         * @return const std::vector<std::unique_ptr<IO::Astrodynamics::OrbitalParameters::StateVector>>&
         */
        [[nodiscard]] const std::vector<IO::Astrodynamics::OrbitalParameters::StateVector> &GetStateVectors() const;

        /**
         * Clear StateOrientations collection handled by this propagator
         */
        void ClearStateOrientations();

        /**
         * Get State orientations generated by propagator
         * @return
         */
        [[nodiscard]] const std::vector<std::vector<IO::Astrodynamics::OrbitalParameters::StateOrientation>>& GetStateOrientations() const;

        /**
         * @brief Get the Latest State Orientation
         * 
         * @return IO::Astrodynamics::OrbitalParameters::StateOrientation*
         */
        [[nodiscard]] const IO::Astrodynamics::OrbitalParameters::StateOrientation* GetLatestStateOrientation() const;
    };

} // namespace IO::Astrodynamics::Propagators

#endif