// Copyright 2023. Sylvain Guillet (sylvain.guillet@tutamail.com)

using System;
using System.Collections.Generic;
using IO.Astrodynamics.CCSDS.Common.Enums;
using IO.Astrodynamics.CCSDS.OMM;
using Xunit;

namespace IO.Astrodynamics.Tests.CCSDS.OMM
{
    public class OmmMetadataTests
    {
        [Fact]
        public void Constructor_WithStrings_Succeeds()
        {
            var metadata = new OmmMetadata(
                objectName: "ISS (ZARYA)",
                objectId: "1998-067A",
                centerName: "EARTH",
                referenceFrame: "TEME",
                timeSystem: "UTC",
                meanElementTheory: "SGP4");

            Assert.Equal("ISS (ZARYA)", metadata.ObjectName);
            Assert.Equal("1998-067A", metadata.ObjectId);
            Assert.Equal("EARTH", metadata.CenterName);
            Assert.Equal("TEME", metadata.ReferenceFrame);
            Assert.Equal("UTC", metadata.TimeSystem);
            Assert.Equal("SGP4", metadata.MeanElementTheory);
        }

        [Fact]
        public void Constructor_WithEnums_Succeeds()
        {
            var metadata = new OmmMetadata(
                objectName: "ISS (ZARYA)",
                objectId: "1998-067A",
                centerName: "EARTH",
                referenceFrame: CcsdsReferenceFrame.TEME,
                timeSystem: CcsdsTimeSystem.UTC,
                meanElementTheory: MeanElementTheory.SGP4);

            Assert.Equal("ISS (ZARYA)", metadata.ObjectName);
            Assert.Equal("TEME", metadata.ReferenceFrame);
            Assert.Equal(CcsdsReferenceFrame.TEME, metadata.ReferenceFrameEnum);
            Assert.Equal("UTC", metadata.TimeSystem);
            Assert.Equal(CcsdsTimeSystem.UTC, metadata.TimeSystemEnum);
            Assert.Equal("SGP4", metadata.MeanElementTheory);
            Assert.Equal(MeanElementTheory.SGP4, metadata.MeanElementTheoryEnum);
        }

        [Fact]
        public void Constructor_ParsesKnownReferenceFrame()
        {
            var metadata = new OmmMetadata(
                "ISS", "1998-067A", "EARTH", "TEME", "UTC", "SGP4");

            Assert.Equal(CcsdsReferenceFrame.TEME, metadata.ReferenceFrameEnum);
        }

        [Fact]
        public void Constructor_UnknownReferenceFrame_ReturnsNull()
        {
            var metadata = new OmmMetadata(
                "ISS", "1998-067A", "EARTH", "CUSTOM_FRAME", "UTC", "SGP4");

            Assert.Null(metadata.ReferenceFrameEnum);
            Assert.Equal("CUSTOM_FRAME", metadata.ReferenceFrame);
        }

        [Fact]
        public void Constructor_ParsesKnownTimeSystem()
        {
            var metadata = new OmmMetadata(
                "ISS", "1998-067A", "EARTH", "TEME", "TDB", "SGP4");

            Assert.Equal(CcsdsTimeSystem.TDB, metadata.TimeSystemEnum);
        }

        [Fact]
        public void Constructor_UnknownTimeSystem_ReturnsNull()
        {
            var metadata = new OmmMetadata(
                "ISS", "1998-067A", "EARTH", "TEME", "CUSTOM_TIME", "SGP4");

            Assert.Null(metadata.TimeSystemEnum);
            Assert.Equal("CUSTOM_TIME", metadata.TimeSystem);
        }

        [Fact]
        public void Constructor_ParsesKnownMeanElementTheory()
        {
            var metadata = new OmmMetadata(
                "ISS", "1998-067A", "EARTH", "TEME", "UTC", "SGP4");

            Assert.Equal(MeanElementTheory.SGP4, metadata.MeanElementTheoryEnum);
        }

        [Fact]
        public void Constructor_UnknownMeanElementTheory_ReturnsNull()
        {
            var metadata = new OmmMetadata(
                "ISS", "1998-067A", "EARTH", "TEME", "UTC", "CUSTOM_THEORY");

            Assert.Null(metadata.MeanElementTheoryEnum);
            Assert.Equal("CUSTOM_THEORY", metadata.MeanElementTheory);
        }

        [Fact]
        public void Constructor_WithReferenceFrameEpoch_Succeeds()
        {
            var epoch = new DateTime(2000, 1, 1, 12, 0, 0, DateTimeKind.Utc);
            var metadata = new OmmMetadata(
                "ISS", "1998-067A", "EARTH", "TEME", "UTC", "SGP4",
                referenceFrameEpoch: epoch);

            Assert.Equal(epoch, metadata.ReferenceFrameEpoch);
        }

        [Fact]
        public void Constructor_WithComments_Succeeds()
        {
            var comments = new List<string> { "Generated by system", "Test data" };
            var metadata = new OmmMetadata(
                "ISS", "1998-067A", "EARTH", "TEME", "UTC", "SGP4",
                comments: comments);

            Assert.Equal(2, metadata.Comments.Count);
            Assert.Equal("Generated by system", metadata.Comments[0]);
        }

        [Fact]
        public void CreateForSgp4_FactoryMethod_Succeeds()
        {
            var metadata = OmmMetadata.CreateForSgp4("ISS (ZARYA)", "1998-067A");

            Assert.Equal("ISS (ZARYA)", metadata.ObjectName);
            Assert.Equal("1998-067A", metadata.ObjectId);
            Assert.Equal("EARTH", metadata.CenterName);
            Assert.Equal("TEME", metadata.ReferenceFrame);
            Assert.Equal(CcsdsReferenceFrame.TEME, metadata.ReferenceFrameEnum);
            Assert.Equal("UTC", metadata.TimeSystem);
            Assert.Equal(CcsdsTimeSystem.UTC, metadata.TimeSystemEnum);
            Assert.Equal("SGP4", metadata.MeanElementTheory);
            Assert.Equal(MeanElementTheory.SGP4, metadata.MeanElementTheoryEnum);
        }

        [Theory]
        [InlineData(null)]
        [InlineData("")]
        [InlineData("   ")]
        public void Constructor_NullOrEmptyObjectName_ThrowsArgumentException(string objectName)
        {
            Assert.Throws<ArgumentException>(() =>
                new OmmMetadata(objectName, "1998-067A", "EARTH", "TEME", "UTC", "SGP4"));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("")]
        [InlineData("   ")]
        public void Constructor_NullOrEmptyObjectId_ThrowsArgumentException(string objectId)
        {
            Assert.Throws<ArgumentException>(() =>
                new OmmMetadata("ISS", objectId, "EARTH", "TEME", "UTC", "SGP4"));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("")]
        [InlineData("   ")]
        public void Constructor_NullOrEmptyCenterName_ThrowsArgumentException(string centerName)
        {
            Assert.Throws<ArgumentException>(() =>
                new OmmMetadata("ISS", "1998-067A", centerName, "TEME", "UTC", "SGP4"));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("")]
        [InlineData("   ")]
        public void Constructor_NullOrEmptyReferenceFrame_ThrowsArgumentException(string referenceFrame)
        {
            Assert.Throws<ArgumentException>(() =>
                new OmmMetadata("ISS", "1998-067A", "EARTH", referenceFrame, "UTC", "SGP4"));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("")]
        [InlineData("   ")]
        public void Constructor_NullOrEmptyTimeSystem_ThrowsArgumentException(string timeSystem)
        {
            Assert.Throws<ArgumentException>(() =>
                new OmmMetadata("ISS", "1998-067A", "EARTH", "TEME", timeSystem, "SGP4"));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("")]
        [InlineData("   ")]
        public void Constructor_NullOrEmptyMeanElementTheory_ThrowsArgumentException(string meanElementTheory)
        {
            Assert.Throws<ArgumentException>(() =>
                new OmmMetadata("ISS", "1998-067A", "EARTH", "TEME", "UTC", meanElementTheory));
        }

        [Fact]
        public void Comments_DefaultsToEmpty()
        {
            var metadata = new OmmMetadata(
                "ISS", "1998-067A", "EARTH", "TEME", "UTC", "SGP4");

            Assert.NotNull(metadata.Comments);
            Assert.Empty(metadata.Comments);
        }

        [Fact]
        public void ToString_ContainsRelevantInfo()
        {
            var metadata = new OmmMetadata(
                "ISS (ZARYA)", "1998-067A", "EARTH", "TEME", "UTC", "SGP4");

            var result = metadata.ToString();

            Assert.Contains("OmmMetadata", result);
            Assert.Contains("ISS", result);
            Assert.Contains("1998-067A", result);
            Assert.Contains("TEME", result);
        }
    }
}
