#include <stdio.h>
#include <math.h>
#include "sofa.h"
#include "sofam.h"

/*
 * Extracts IAU 2000B nutation coefficients by evaluating SOFA's iauNut00b
 * at many carefully chosen epochs and fitting the individual term contributions.
 *
 * Instead, we use an alternative approach: we call iauNut06a (full 2000A)
 * at many epochs and output dpsi/deps for validation.
 * We also output the precession angles for validation.
 */

int main() {
    /* Print SOFA values at key test epochs for validation */
    double epochs[][2] = {
        {DJ00, 0.0},              /* J2000.0 TT */
        {DJM0, 53736.0},         /* SOFA test date */
        {DJ00, 8766.5},          /* 2024-Jan-01 */
        {DJM0, 55362.0},         /* 2010-Jun-15 */
        {DJ00, 3652.5},          /* 2010-01-01 */
        {DJ00, -3652.5},         /* 1990-01-01 */
        {DJ00, 18262.5},         /* 2050-01-01 */
    };
    int nepochs = sizeof(epochs) / sizeof(epochs[0]);

    printf("// SOFA reference values for nutation validation\n");
    printf("// Generated by extract_nut00b.c using SOFA library\n\n");

    for (int i = 0; i < nepochs; i++) {
        double jd1 = epochs[i][0], jd2 = epochs[i][1];
        double t = ((jd1 - DJ00) + jd2) / DJC;

        /* Full IAU 2006/2000A nutation */
        double dpsi_a, deps_a;
        iauNut06a(jd1, jd2, &dpsi_a, &deps_a);

        /* IAU 2000B nutation (77 terms) */
        double dpsi_b, deps_b;
        iauNut00b(jd1, jd2, &dpsi_b, &deps_b);

        /* Precession angles (IAU 2006) */
        double eps0, psia, oma, bpa, bqa, pia, bpia,
               epsa, chia, za, zetaa, thetaa, pa, gam, phi, psi;
        iauP06e(jd1, jd2, &eps0, &psia, &oma, &bpa, &bqa, &pia, &bpia,
                &epsa, &chia, &za, &zetaa, &thetaa, &pa, &gam, &phi, &psi);

        /* CIP X,Y from series */
        double x, y;
        iauXy06(jd1, jd2, &x, &y);

        /* CIO locator s */
        double s = iauS06(jd1, jd2, x, y);

        /* Frame bias values */
        double dpsibi, depsbi, dra0;
        iauBi00(&dpsibi, &depsbi, &dra0);

        printf("// Epoch %d: t = %.17e centuries TT\n", i, t);
        printf("//   dpsi_2000A = %.17e rad (%.6f mas)\n", dpsi_a, dpsi_a / DAS2R * 1000.0);
        printf("//   deps_2000A = %.17e rad (%.6f mas)\n", deps_a, deps_a / DAS2R * 1000.0);
        printf("//   dpsi_2000B = %.17e rad (%.6f mas)\n", dpsi_b, dpsi_b / DAS2R * 1000.0);
        printf("//   deps_2000B = %.17e rad (%.6f mas)\n", deps_b, deps_b / DAS2R * 1000.0);
        printf("//   dpsi diff  = %.6f µas\n", (dpsi_a - dpsi_b) / DAS2R * 1e6);
        printf("//   deps diff  = %.6f µas\n", (deps_a - deps_b) / DAS2R * 1e6);
        printf("//   epsa       = %.17e rad\n", epsa);
        printf("//   psia       = %.17e rad\n", psia);
        printf("//   oma        = %.17e rad\n", oma);
        printf("//   chia       = %.17e rad\n", chia);
        printf("//   eps0       = %.17e rad\n", eps0);
        printf("//   X          = %.17e rad\n", x);
        printf("//   Y          = %.17e rad\n", y);
        printf("//   s          = %.17e rad\n", s);
        if (i == 0) {
            printf("//   dpsibi     = %.17e rad\n", dpsibi);
            printf("//   depsbi     = %.17e rad\n", depsbi);
            printf("//   dra0       = %.17e rad\n", dra0);
        }
        printf("\n");
    }

    /* Print the frame bias values */
    double dpsibi, depsbi, dra0;
    iauBi00(&dpsibi, &depsbi, &dra0);
    printf("// Frame bias (IERS 2006):\n");
    printf("//   dpsibi = %.17e rad = %.6f mas\n", dpsibi, dpsibi / DAS2R * 1000.0);
    printf("//   depsbi = %.17e rad = %.6f mas\n", depsbi, depsbi / DAS2R * 1000.0);
    printf("//   dra0   = %.17e rad = %.6f mas\n", dra0, dra0 / DAS2R * 1000.0);
    printf("//   eps0   = %.17e rad = %.6f\"\n", 84381.406 * DAS2R, 84381.406);

    /* Print ERA validation */
    printf("\n// ERA values:\n");
    printf("//   ERA at J2000 UT1: %.17e rad\n", iauEra00(DJ00, 0.0));
    printf("//   ERA at J2000+1d:  %.17e rad\n", iauEra00(DJ00, 1.0));

    return 0;
}
