// Copyright 2026. Sylvain Guillet (sylvain.guillet@tutamail.com)
// Generated by tools/sofa_reference/extract_s06.c from the SOFA iauS06 source. Do not edit by hand.
namespace IO.Astrodynamics.Frames;

/// <summary>
/// Series of the IAU 2006 CIO locator <c>s + XY/2</c> (IERS Conventions 2010, Table 5.2d), as
/// implemented by SOFA iauS06: a polynomial plus 66 periodic terms grouped by power of t.
/// Amplitudes are in microarcseconds. The integer multipliers apply to the fundamental arguments
/// l, l', F, D, Omega, the mean longitudes of Venus and Earth, and the general precession pA.
/// </summary>
internal static class Iau2006CioLocatorData
{
    /// <summary>
    /// Polynomial part, coefficients of t^0 to t^5 (microarcseconds).
    /// </summary>
    internal static readonly double[] Polynomial = [94.00, 3808.65, -122.68, -72574.11, 27.98, 15.62];

    internal static readonly (int l, int lp, int f, int d, int om, int lve, int le, int pa, double s, double c)[] Order0 =
    [
        (0, 0, 0, 0, 1, 0, 0, 0, -2640.73, 0.39),
        (0, 0, 0, 0, 2, 0, 0, 0, -63.53, 0.02),
        (0, 0, 2, -2, 3, 0, 0, 0, -11.75, -0.01),
        (0, 0, 2, -2, 1, 0, 0, 0, -11.21, -0.01),
        (0, 0, 2, -2, 2, 0, 0, 0, 4.57, 0.00),
        (0, 0, 2, 0, 3, 0, 0, 0, -2.02, 0.00),
        (0, 0, 2, 0, 1, 0, 0, 0, -1.98, 0.00),
        (0, 0, 0, 0, 3, 0, 0, 0, 1.72, 0.00),
        (0, 1, 0, 0, 1, 0, 0, 0, 1.41, 0.01),
        (0, 1, 0, 0, -1, 0, 0, 0, 1.26, 0.01),
        (1, 0, 0, 0, -1, 0, 0, 0, 0.63, 0.00),
        (1, 0, 0, 0, 1, 0, 0, 0, 0.63, 0.00),
        (0, 1, 2, -2, 3, 0, 0, 0, -0.46, 0.00),
        (0, 1, 2, -2, 1, 0, 0, 0, -0.45, 0.00),
        (0, 0, 4, -4, 4, 0, 0, 0, -0.36, 0.00),
        (0, 0, 1, -1, 1, -8, 12, 0, 0.24, 0.12),
        (0, 0, 2, 0, 0, 0, 0, 0, -0.32, 0.00),
        (0, 0, 2, 0, 2, 0, 0, 0, -0.28, 0.00),
        (1, 0, 2, 0, 3, 0, 0, 0, -0.27, 0.00),
        (1, 0, 2, 0, 1, 0, 0, 0, -0.26, 0.00),
        (0, 0, 2, -2, 0, 0, 0, 0, 0.21, 0.00),
        (0, 1, -2, 2, -3, 0, 0, 0, -0.19, 0.00),
        (0, 1, -2, 2, -1, 0, 0, 0, -0.18, 0.00),
        (0, 0, 0, 0, 0, 8, -13, -1, 0.10, -0.05),
        (0, 0, 0, 2, 0, 0, 0, 0, -0.15, 0.00),
        (2, 0, -2, 0, -1, 0, 0, 0, 0.14, 0.00),
        (0, 1, 2, -2, 2, 0, 0, 0, 0.14, 0.00),
        (1, 0, 0, -2, 1, 0, 0, 0, -0.14, 0.00),
        (1, 0, 0, -2, -1, 0, 0, 0, -0.14, 0.00),
        (0, 0, 4, -2, 4, 0, 0, 0, -0.13, 0.00),
        (0, 0, 2, -2, 4, 0, 0, 0, 0.11, 0.00),
        (1, 0, -2, 0, -3, 0, 0, 0, -0.11, 0.00),
        (1, 0, -2, 0, -1, 0, 0, 0, -0.11, 0.00)
    ];

    internal static readonly (int l, int lp, int f, int d, int om, int lve, int le, int pa, double s, double c)[] Order1 =
    [
        (0, 0, 0, 0, 2, 0, 0, 0, -0.07, 3.57),
        (0, 0, 0, 0, 1, 0, 0, 0, 1.73, -0.03),
        (0, 0, 2, -2, 3, 0, 0, 0, 0.00, 0.48)
    ];

    internal static readonly (int l, int lp, int f, int d, int om, int lve, int le, int pa, double s, double c)[] Order2 =
    [
        (0, 0, 0, 0, 1, 0, 0, 0, 743.52, -0.17),
        (0, 0, 2, -2, 2, 0, 0, 0, 56.91, 0.06),
        (0, 0, 2, 0, 2, 0, 0, 0, 9.84, -0.01),
        (0, 0, 0, 0, 2, 0, 0, 0, -8.85, 0.01),
        (0, 1, 0, 0, 0, 0, 0, 0, -6.38, -0.05),
        (1, 0, 0, 0, 0, 0, 0, 0, -3.07, 0.00),
        (0, 1, 2, -2, 2, 0, 0, 0, 2.23, 0.00),
        (0, 0, 2, 0, 1, 0, 0, 0, 1.67, 0.00),
        (1, 0, 2, 0, 2, 0, 0, 0, 1.30, 0.00),
        (0, 1, -2, 2, -2, 0, 0, 0, 0.93, 0.00),
        (1, 0, 0, -2, 0, 0, 0, 0, 0.68, 0.00),
        (0, 0, 2, -2, 1, 0, 0, 0, -0.55, 0.00),
        (1, 0, -2, 0, -2, 0, 0, 0, 0.53, 0.00),
        (0, 0, 0, 2, 0, 0, 0, 0, -0.27, 0.00),
        (1, 0, 0, 0, 1, 0, 0, 0, -0.27, 0.00),
        (1, 0, -2, -2, -2, 0, 0, 0, -0.26, 0.00),
        (1, 0, 0, 0, -1, 0, 0, 0, -0.25, 0.00),
        (1, 0, 2, 0, 1, 0, 0, 0, 0.22, 0.00),
        (2, 0, 0, -2, 0, 0, 0, 0, -0.21, 0.00),
        (2, 0, -2, 0, -1, 0, 0, 0, 0.20, 0.00),
        (0, 0, 2, 2, 2, 0, 0, 0, 0.17, 0.00),
        (2, 0, 2, 0, 2, 0, 0, 0, 0.13, 0.00),
        (2, 0, 0, 0, 0, 0, 0, 0, -0.13, 0.00),
        (1, 0, 2, -2, 2, 0, 0, 0, -0.12, 0.00),
        (0, 0, 2, 0, 0, 0, 0, 0, -0.11, 0.00)
    ];

    internal static readonly (int l, int lp, int f, int d, int om, int lve, int le, int pa, double s, double c)[] Order3 =
    [
        (0, 0, 0, 0, 1, 0, 0, 0, 0.30, -23.42),
        (0, 0, 2, -2, 2, 0, 0, 0, -0.03, -1.46),
        (0, 0, 2, 0, 2, 0, 0, 0, -0.01, -0.25),
        (0, 0, 0, 0, 2, 0, 0, 0, 0.00, 0.23)
    ];

    internal static readonly (int l, int lp, int f, int d, int om, int lve, int le, int pa, double s, double c)[] Order4 =
    [
        (0, 0, 0, 0, 1, 0, 0, 0, -0.26, -0.01)
    ];

    /// <summary>
    /// Periodic terms: <c>Series[k]</c> multiplies t^k. Each term adds <c>s sin(a) + c cos(a)</c>,
    /// where a is the integer combination of the eight fundamental arguments.
    /// </summary>
    internal static readonly (int l, int lp, int f, int d, int om, int lve, int le, int pa, double s, double c)[][] Series =
        [Order0, Order1, Order2, Order3, Order4];
}
