name: IO SDK documentation

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate docs
      uses: mattnotmitt/doxygen-action@1.9.5
      
    - name: Commit generated docs
      run: |
        git config --global user.name 'Sylvain Guillet'
        git config --global user.email 'sylvain.guillet@live.com'
        git branch
        git add Docs/
        git commit -am "update docs [skip ci]"      
        git push origin HEAD:develop --force
